import type { Journey, Moment, Source, Theme } from './types'
import extensions from '../../../data/atlas/extensions.json' with { type: 'json' }
import trancheTwo from '../../../data/atlas/tranche-two.json' with { type: 'json' }

const source = (title: string, url: string): Source => ({ title, url })
const s = {
  writing: source(
    'British Museum · How to write cuneiform',
    'https://www.britishmuseum.org/blog/how-write-cuneiform',
  ),
  silk: source(
    'UNESCO · The Chang’an–Tianshan Silk Roads',
    'https://whc.unesco.org/en/list/1442',
  ),
  print: source(
    'British Library · The Diamond Sutra',
    'https://idp.bl.uk/blog/the-diamond-sutra/',
  ),
  zimbabwe: source(
    'The Met · Great Zimbabwe',
    'https://www.metmuseum.org/essays/great-zimbabwe',
  ),
  inca: source(
    'UNESCO · Historic Sanctuary of Machu Picchu',
    'https://whc.unesco.org/en/list/274',
  ),
  charter: source(
    'The National Archives · Magna Carta',
    'https://www.nationalarchives.gov.uk/explore-the-collection/explore-by-time-period/medieval/magna-carta/',
  ),
  plague: source(
    'The National Archives · Living in the 14th century',
    'https://www.nationalarchives.gov.uk/currency-converter/living-in-the-14th-century/',
  ),
  steam: source(
    'Science Museum · Watt’s separate condenser',
    'https://blog.sciencemuseum.org.uk/james-watt-and-the-separate-condenser/',
  ),
  haiti: source(
    'Office of the Historian · The Haitian Revolution',
    'https://history.state.gov/milestones/1784-1800/haitian-rev',
  ),
  vaccine: source(
    'WHO · History of smallpox vaccination',
    'https://www.who.int/news-room/spotlight/history-of-vaccination/history-of-smallpox-vaccination',
  ),
  smallpox: source(
    'WHO · Smallpox',
    'https://www.who.int/emergencies/situations/smallpox/',
  ),
  vote: source(
    'NZ History · Women and the vote',
    'https://nzhistory.govt.nz/politics/womens-suffrage',
  ),
  india: source(
    'National Army Museum · Independence and Partition',
    'https://www.nam.ac.uk/explore/independence-and-partition-1947',
  ),
  australia: source(
    'National Museum of Australia · Indigenous referendum',
    'https://www.nma.gov.au/defining-moments/resources/indigenous-referendum',
  ),
  web: source(
    'CERN · The birth of the Web',
    'https://home.cern/science/computing/the-birth-of-the-web/',
  ),
  mandela: source(
    'Nelson Mandela Foundation · Democracy',
    'https://www.nelsonmandela.org/democracy',
  ),
}

function moment(
  id: string,
  year: number,
  title: string,
  place: string,
  region: string,
  coordinates: [number, number],
  theme: Theme,
  tags: string[],
  hook: string,
  story: string,
  consequence: string,
  caution: string,
  sources: Source[],
  extra: Partial<Moment> = {},
): Moment {
  return {
    id,
    year,
    title,
    place,
    region,
    coordinates,
    theme,
    tags,
    hook,
    story,
    consequence,
    caution,
    sources,
    ...extra,
  }
}

// Curated connections are editorial interpretations, never measured causal effects.
// Coordinates identify an illustrative anchor place, not an event’s full footprint.
export const moments: Moment[] = [
  moment(
    'writing',
    -3200,
    'When memory left the mind',
    'Uruk · Mesopotamia',
    'Asia',
    [45.64, 31.32],
    'ideas',
    ['information', 'networks', 'technology'],
    'Before books, there were beer receipts.',
    'In growing cities, people pressed marks into clay to keep track of goods. Writing made it possible for a message to outlive its maker.',
    'Information could travel beyond one person’s memory.',
    'Writing emerged in several societies. This is one early tradition, not the origin of every script.',
    [s.writing],
    { approximate: true },
  ),
  moment(
    'silk',
    -130,
    'The world starts to weave',
    'Chang’an · Han China',
    'Asia',
    [108.94, 34.34],
    'connection',
    ['trade', 'networks', 'exchange'],
    'A road can carry far more than silk.',
    'Diplomatic journeys helped connect Han China with Central Asia. Over time, a web of routes carried goods, skills, religions, and stories between communities.',
    'Distant people became part of one another’s lives.',
    'There was no single Silk Road, opening day, or end-to-end route used by every trader.',
    [s.silk],
    { approximate: true },
  ),
  moment(
    'baghdad',
    762,
    'A city made for ideas',
    'Baghdad · Abbasid Caliphate',
    'Asia',
    [44.37, 33.31],
    'ideas',
    ['cities', 'knowledge', 'exchange'],
    'What if the world’s knowledge met in one city?',
    'The new Abbasid capital grew into a major centre of learning. Scholars working in Arabic translated, debated, and developed knowledge from many traditions.',
    'Translation helped ideas cross languages and generations.',
    'The translation movement unfolded over centuries, not in one library or one year.',
    [
      source(
        'Encyclopaedia Britannica · Baghdad: History',
        'https://www.britannica.com/place/Baghdad/History',
      ),
    ],
  ),
  moment(
    'diamond',
    868,
    'One block. A thousand voices.',
    'Dunhuang · Tang China',
    'Asia',
    [94.66, 40.14],
    'ideas',
    ['information', 'networks', 'technology'],
    'A book made to be shared, six centuries before Gutenberg.',
    'A surviving copy of the Diamond Sutra bears the date 868. Woodblock printing let people reproduce pages instead of copying each one by hand.',
    'The same words could reach many more readers.',
    'This is the earliest complete dated printed book known to survive. It is not the first thing ever printed.',
    [s.print],
  ),
  moment(
    'zimbabwe',
    1200,
    'A stone city, an ocean of connections',
    'Great Zimbabwe',
    'Africa',
    [30.93, -20.27],
    'connection',
    ['trade', 'cities', 'exchange'],
    'Seashells and imported ceramics, hundreds of miles from the sea.',
    'Great Zimbabwe linked the southern African interior to Indian Ocean trade. Its great stone enclosures stood within a much wider network of people and goods.',
    'An inland African city participated in long-distance exchange.',
    'The city developed over centuries. This date is an anchor within that growth, not a foundation date.',
    [s.zimbabwe],
    { approximate: true, endYear: 1450 },
  ),
  moment(
    'charter',
    1215,
    'Even a king has limits',
    'Runnymede · England',
    'Europe',
    [-0.57, 51.44],
    'power',
    ['rights', 'institutions', 'resistance'],
    'A king meets people who can say no.',
    'Rebellious barons forced King John to agree to Magna Carta. The first agreement failed, but later versions helped keep the idea of limits on royal power alive.',
    'A settlement became a symbol used by later generations.',
    'This was not a promise of equal rights for everyone. Many protections served a privileged minority.',
    [s.charter],
  ),
  moment(
    'musa',
    1324,
    'The journey that put Mali on the map',
    'Mali Empire · West Africa',
    'Africa',
    [-3, 16.77],
    'connection',
    ['trade', 'networks', 'exchange'],
    'One pilgrimage made distant people talk about an African empire.',
    'Mansa Musa travelled to Mecca with a famous display of wealth. The journey strengthened Mali’s visibility in the wider Islamic world.',
    'People far away learned about the wealth and reach of Mali.',
    'Accounts of his wealth vary. Modern claims that he was “the richest ever” cannot be reliably measured.',
    [
      source(
        'Encyclopaedia Britannica · Mūsā I of Mali',
        'https://www.britannica.com/biography/Musa-I-of-Mali',
      ),
    ],
  ),
  moment(
    'plague',
    1348,
    'When the world fell quiet',
    'Weymouth · England',
    'Europe',
    [-2.46, 50.61],
    'survival',
    ['disease', 'labour', 'disruption'],
    'After catastrophe, who gets to set the rules of work?',
    'The Black Death reached England in 1348. Enormous loss of life disrupted communities and left survivors in a world where labour was suddenly scarcer.',
    'Landowners and workers faced a changed balance of power.',
    'Outcomes differed by region. This English anchor represents one part of a much wider pandemic.',
    [s.plague],
  ),
  moment(
    'inca',
    1450,
    'A city among the clouds',
    'Machu Picchu · Inca world',
    'South America',
    [-72.55, -13.16],
    'power',
    ['cities', 'infrastructure', 'institutions'],
    'A mountain becomes a place to live.',
    'Inca builders fitted stone buildings, terraces, and water channels into a steep Andean landscape. The site reveals extraordinary skill in adapting to place.',
    'Engineering connected human life to a demanding environment.',
    'The date is approximate. The site’s precise functions and early chronology remain subjects of research.',
    [s.inca],
    { approximate: true },
  ),
  moment(
    'gutenberg',
    1455,
    'The copy becomes the revolution',
    'Mainz · German lands',
    'Europe',
    [8.27, 50],
    'ideas',
    ['information', 'networks', 'technology'],
    'What happens when words become much easier to copy?',
    'Gutenberg’s Bible showed what movable metal type could achieve in Europe. Over the following decades, printers helped books and arguments circulate more widely.',
    'Publishing expanded the reach of knowledge and disagreement.',
    'Printing and movable type already had long histories in East Asia. Cheaper books did not instantly create universal literacy.',
    [
      source(
        'Library of Congress · Gutenberg Bible',
        'https://www.loc.gov/exhibits/bibles/the-gutenberg-bible.html',
      ),
    ],
  ),
  moment(
    'atlantic',
    1492,
    'Two worlds, a devastating collision',
    'Caribbean',
    'North America',
    [-74.5, 24],
    'connection',
    ['trade', 'exchange', 'disruption'],
    'Connection can transform the world—and destroy lives.',
    'Columbus’s voyage began sustained contact between Europe and the Americas. Colonisation, forced labour, and disease devastated Indigenous communities.',
    'People, plants, animals, and pathogens crossed the Atlantic on an unprecedented scale.',
    'The Americas were already home to complex societies. This was not the discovery of an empty world.',
    [
      source(
        'Library of Congress · 1492: An Ongoing Voyage',
        'https://www.loc.gov/exhibits/1492/',
      ),
    ],
  ),
  moment(
    'reformation',
    1517,
    'An argument that would not stay local',
    'Wittenberg · German lands',
    'Europe',
    [12.64, 51.87],
    'ideas',
    ['information', 'resistance', 'institutions'],
    'A debate about faith spreads far beyond one town.',
    'Martin Luther’s challenge to church practices became part of a wider religious upheaval. Print helped arguments travel, while rulers and communities chose different paths.',
    'Authority in western Christianity fractured.',
    'Printing helped circulate debate; it did not cause the Reformation on its own.',
    [
      source(
        'Encyclopaedia Britannica · Reformation',
        'https://www.britannica.com/event/Reformation',
      ),
    ],
  ),
  moment(
    'steam',
    1769,
    'A different kind of muscle',
    'Glasgow · Scotland',
    'Europe',
    [-4.25, 55.86],
    'ideas',
    ['technology', 'labour', 'disruption'],
    'A machine begins to change what human work can be.',
    'James Watt patented a separate condenser that made steam engines more efficient. Practical engines and factories developed through many people’s work over the years that followed.',
    'New energy sources helped reshape production and work.',
    '1769 marks a patent, not a single start date for the Industrial Revolution. Its gains and costs were uneven.',
    [s.steam],
  ),
  moment(
    'america',
    1776,
    'Who gets to be free?',
    'Philadelphia · North America',
    'North America',
    [-75.16, 39.95],
    'freedom',
    ['rights', 'resistance', 'institutions'],
    'A declaration makes a promise its society does not yet keep.',
    'Thirteen colonies declared independence from Britain. Their language of equality became powerful, even while slavery and exclusion continued.',
    'Later movements could challenge the gap between ideals and reality.',
    'Independence did not bring equal citizenship to enslaved people, Indigenous nations, or women.',
    [
      source(
        'US National Archives · Declaration of Independence',
        'https://www.archives.gov/founding-docs/declaration',
      ),
    ],
  ),
  moment(
    'france',
    1789,
    'A world turned upside down',
    'Paris · France',
    'Europe',
    [2.35, 48.86],
    'freedom',
    ['rights', 'resistance', 'institutions'],
    'What happens when inherited power loses its grip?',
    'Financial crisis and political conflict helped spark the French Revolution. Demands for rights transformed public life, followed by war, repression, and new forms of rule.',
    'The language of citizenship travelled far beyond France.',
    'The Revolution was not one united movement, and its promises were applied unequally.',
    [
      source(
        'Encyclopaedia Britannica · French Revolution',
        'https://www.britannica.com/event/French-Revolution',
      ),
    ],
  ),
  moment(
    'haiti',
    1791,
    'Freedom is not a gift',
    'Saint-Domingue · Haiti',
    'North America',
    [-72.2, 19.76],
    'freedom',
    ['rights', 'resistance', 'institutions'],
    'People treated as property fight to build a country.',
    'Enslaved people rose against the plantation system in the French colony of Saint-Domingue. Years of struggle led to independent Haiti in 1804.',
    'A revolution overthrew slavery and colonial rule.',
    'Independence brought isolation and new struggles. Freedom did not erase the damage of slavery or guarantee prosperity.',
    [s.haiti],
    { endYear: 1804 },
  ),
  moment(
    'jenner',
    1796,
    'A small experiment, a vast possibility',
    'Berkeley · England',
    'Europe',
    [-2.46, 51.69],
    'survival',
    ['disease', 'knowledge', 'cooperation'],
    'Could one infection protect against another?',
    'Edward Jenner tested protection against smallpox using cowpox material. His work built on earlier practices and helped vaccination spread.',
    'Prevention offered a new way to fight a deadly disease.',
    'The experiment would not meet modern research ethics. Earlier inoculation traditions existed in Africa and Asia.',
    [s.vaccine],
  ),
  moment(
    'bolivar',
    1819,
    'An empire begins to unravel',
    'Boyacá · New Granada',
    'South America',
    [-73.43, 5.45],
    'freedom',
    ['rights', 'resistance', 'institutions'],
    'Winning independence is only the beginning.',
    'Victory at Boyacá helped independence forces break Spanish control in New Granada. Building lasting political settlements proved much harder than winning a battle.',
    'New states emerged from the struggle against empire.',
    'Independence did not remove deep inequalities, and the region’s peoples did not share a single political aim.',
    [
      source(
        'Encyclopaedia Britannica · Battle of Boyacá',
        'https://www.britannica.com/event/Battle-of-Boyaca',
      ),
    ],
  ),
  moment(
    'telegraph',
    1858,
    'The ocean gets a voice',
    'Valentia · Ireland',
    'Europe',
    [-10.35, 51.93],
    'connection',
    ['information', 'networks', 'technology'],
    'Weeks at sea become a message through a wire.',
    'The first transatlantic telegraph cable briefly linked Europe and North America. It failed after weeks, but a more durable connection followed in 1866.',
    'Long-distance communication began to separate from the speed of ships.',
    'Early connections were fragile, expensive, and controlled by a small number of institutions.',
    [
      source(
        'Science Museum · The first transatlantic telegraph cable',
        'https://blog.sciencemuseum.org.uk/sending-messages-across-the-atlantic-156-years-on-from-the-first-transatlantic-cable/',
      ),
    ],
  ),
  moment(
    'civil-war',
    1861,
    'A nation breaks over slavery',
    'United States',
    'North America',
    [-77.04, 38.9],
    'power',
    ['rights', 'resistance', 'disruption'],
    'An unresolved injustice tears a country apart.',
    'Southern states seceded to protect slavery, and civil war followed. Union victory was followed by the constitutional abolition of slavery in 1865.',
    'Emancipation changed the law, while struggles over freedom and citizenship continued.',
    'The war cannot be reduced to an abstract generational mood. Slavery was central to secession.',
    [
      source(
        'US National Park Service · Slavery: Cause and Catalyst',
        'https://www.nps.gov/civilwar/causes.htm',
      ),
    ],
    { endYear: 1865 },
  ),
  moment(
    'meiji',
    1868,
    'A country rewrites its future',
    'Tokyo · Japan',
    'Asia',
    [139.69, 35.68],
    'power',
    ['technology', 'institutions', 'disruption'],
    'How much can a society change in a generation?',
    'The fall of the Tokugawa shogunate brought a new government under the emperor. Reforms reshaped schooling, the military, industry, and daily life.',
    'Japan rapidly expanded its industrial and state power.',
    'Modernisation had losers as well as winners, and was followed by imperial expansion.',
    [
      source(
        'Encyclopaedia Britannica · Meiji Restoration',
        'https://www.britannica.com/event/Meiji-Restoration',
      ),
    ],
  ),
  moment(
    'nz-vote',
    1893,
    'A petition becomes a possibility',
    'Wellington · Aotearoa New Zealand',
    'Oceania',
    [174.78, -41.29],
    'freedom',
    ['rights', 'resistance', 'participation'],
    'Thousands of signatures. A door opens.',
    'After years of campaigning, women won the vote in New Zealand’s parliamentary elections. They went to the polls later that year.',
    'Organised public pressure expanded political participation.',
    'Women could vote but could not yet stand for Parliament; that right followed in 1919.',
    [s.vote],
  ),
  moment(
    'flu',
    1918,
    'An invisible traveller',
    'Global · anchor in North America',
    'North America',
    [-98.58, 39.83],
    'survival',
    ['disease', 'networks', 'disruption'],
    'The routes that connect us can also carry danger.',
    'An influenza pandemic spread through a world already at war. Communities tried measures including isolation and restrictions on gatherings.',
    'A connected world faced a shared health emergency with unequal resources.',
    'The place of origin is debated. This map point is an illustrative anchor, not a claim about where it began.',
    [
      source(
        'CDC · 1918 Pandemic',
        'https://archive.cdc.gov/www_cdc_gov/flu/pandemic-resources/1918-pandemic-h1n1.html',
      ),
    ],
  ),
  moment(
    'crash',
    1929,
    'When confidence disappears',
    'New York · United States',
    'North America',
    [-74.01, 40.71],
    'survival',
    ['finance', 'networks', 'disruption'],
    'A financial shock travels into ordinary kitchens.',
    'The Wall Street crash became a symbol of the Great Depression. Bank failures, unemployment, and shrinking trade damaged lives around the world.',
    'Debates about the role of government changed profoundly.',
    'The stock-market crash was not the only cause of the Depression. Countries experienced different timings and depths.',
    [
      source(
        'Federal Reserve History · The Great Depression',
        'https://www.federalreservehistory.org/essays/great-depression',
      ),
    ],
  ),
  moment(
    'un',
    1945,
    'Trying to build a different peace',
    'San Francisco · United States',
    'North America',
    [-122.42, 37.77],
    'power',
    ['institutions', 'cooperation', 'rights'],
    'After catastrophe, can countries write better rules?',
    'Representatives of 50 countries met to create the United Nations. The new organisation aimed to support international cooperation after the Second World War.',
    'An international institution offered tools for diplomacy and collective action.',
    'The UN did not end war. Unequal power was built into its structure, including the Security Council veto.',
    [
      source(
        'United Nations · History of the United Nations',
        'https://www.un.org/en/about-us/history-of-the-un',
      ),
    ],
  ),
  moment(
    'india',
    1947,
    'Freedom, and a line through lives',
    'Delhi · South Asia',
    'Asia',
    [77.21, 28.61],
    'freedom',
    ['rights', 'resistance', 'disruption'],
    'Independence arrives with both hope and heartbreak.',
    'British rule ended and India and Pakistan became independent. Partition uprooted millions and was accompanied by terrible violence.',
    'New states began their lives amid mass displacement.',
    'Experiences differed across communities. Independence and Partition belong in the same story.',
    [s.india],
  ),
  moment(
    'ghana',
    1957,
    'A new flag, a wider horizon',
    'Accra · Ghana',
    'Africa',
    [-0.19, 5.56],
    'freedom',
    ['rights', 'resistance', 'institutions'],
    'One country’s independence becomes a signal to others.',
    'Ghana became independent from British rule under Kwame Nkrumah. Its independence inspired anti-colonial movements elsewhere in Africa.',
    'Decolonisation opened new political possibilities.',
    'Independence was not the end of unequal economic relationships or domestic political conflict.',
    [
      source(
        'Office of the Historian · Ghana',
        'https://history.state.gov/countries/ghana',
      ),
    ],
  ),
  moment(
    'australia',
    1967,
    'Being counted, changing the rules',
    'Canberra · Australia',
    'Oceania',
    [149.13, -35.28],
    'freedom',
    ['rights', 'resistance', 'participation'],
    'A vote changes a constitution, not every life overnight.',
    'Australians voted to remove constitutional exclusions affecting Aboriginal people, including exclusion from population counts, and expand federal law-making power.',
    'A major campaign achieved an important constitutional change.',
    'The referendum did not first grant Aboriginal people citizenship or voting rights. Those are common myths.',
    [s.australia],
  ),
  moment(
    'moon',
    1969,
    'A different view of home',
    'Moon landing · Houston anchor',
    'North America',
    [-95.1, 29.55],
    'ideas',
    ['technology', 'knowledge', 'cooperation'],
    'People reach another world—and look back at this one.',
    'Apollo 11 put the first humans on the Moon. The achievement depended on a vast network of people, public investment, and earlier scientific work.',
    'An extraordinary shared effort expanded what seemed possible.',
    'This map point marks mission control on Earth. The mission also belonged to Cold War competition.',
    [source('NASA · Apollo 11', 'https://www.nasa.gov/mission/apollo-11/')],
  ),
  moment(
    'smallpox',
    1980,
    'The disease that lost',
    'Global · WHO, Geneva',
    'Europe',
    [6.14, 46.22],
    'survival',
    ['disease', 'knowledge', 'cooperation'],
    'For once, humanity makes a disease history.',
    'The World Health Assembly declared smallpox eradicated after a global effort involving vaccination, surveillance, and local health workers.',
    'A human infectious disease was eliminated worldwide.',
    'Success depended on this disease’s particular biology and sustained cooperation. Not every disease can be tackled in the same way.',
    [s.smallpox],
  ),
  moment(
    'berlin',
    1989,
    'The night a wall became a doorway',
    'Berlin · Germany',
    'Europe',
    [13.38, 52.52],
    'freedom',
    ['rights', 'resistance', 'participation'],
    'Something that seemed permanent suddenly is not.',
    'After months of pressure for change, East German border crossings opened on 9 November. Crowds crossed a barrier that had divided lives for decades.',
    'The opening became a symbol of the end of Europe’s Cold War division.',
    'The moment followed long campaigns and wider changes. A single night did not settle every division.',
    [
      source(
        'The Wall Museum · The fall of the Berlin Wall',
        'https://thewallmuseum.com/en/about-the-wall/',
      ),
    ],
  ),
  moment(
    'web',
    1993,
    'A world one click away',
    'CERN · Switzerland',
    'Europe',
    [6.05, 46.23],
    'ideas',
    ['information', 'networks', 'technology'],
    'An invention becomes more powerful when others can build on it.',
    'CERN made World Wide Web software available in the public domain. A system first proposed in 1989 could grow through open use and shared standards.',
    'Publishing and linking information became possible on a new scale.',
    'The Web is not the same thing as the internet. Access and control have always been uneven.',
    [s.web],
  ),
  moment(
    'south-africa',
    1994,
    'The queue that changed a country',
    'Johannesburg · South Africa',
    'Africa',
    [28.05, -26.2],
    'freedom',
    ['rights', 'resistance', 'participation'],
    'For millions, a first ballot carries a lifetime of waiting.',
    'South Africa held its first democratic national elections open to adults of all races. Negotiations and decades of struggle brought apartheid rule to an end.',
    'Political participation expanded on a historic scale.',
    'Democracy did not immediately undo apartheid’s economic and social inequalities.',
    [s.mandela],
  ),
  moment(
    'finance',
    2008,
    'Too connected to stay local',
    'New York · Global finance',
    'North America',
    [-73.98, 40.75],
    'survival',
    ['finance', 'networks', 'disruption'],
    'How does a mortgage problem become a world problem?',
    'Failures in housing finance and a deeply connected banking system triggered a global financial crisis. Jobs, savings, and public budgets suffered.',
    'Governments intervened and financial regulation became a major public debate.',
    'The crisis echoed earlier financial panics, but financial products and policy responses were different.',
    [
      source(
        'Federal Reserve History · The Great Recession',
        'https://www.federalreservehistory.org/essays/great-recession-and-its-aftermath',
      ),
    ],
  ),
  moment(
    'covid',
    2020,
    'The world pauses together',
    'Global · Wuhan anchor',
    'Asia',
    [114.3, 30.59],
    'survival',
    ['disease', 'networks', 'disruption'],
    'Across the world, ordinary routines suddenly change.',
    'COVID-19 became a pandemic. Health systems, work, education, and travel were disrupted, while scientists and communities mobilised in response.',
    'Global connection made both spread and scientific cooperation possible.',
    'Wuhan marks the first reported outbreak, not a resolved claim about the virus’s ultimate origin. Experiences varied greatly.',
    [
      source(
        'WHO · Coronavirus disease (COVID-19) pandemic',
        'https://www.who.int/emergencies/diseases/novel-coronavirus-2019',
      ),
    ],
  ),
]
  .concat(extensions as Moment[])
  .concat(trancheTwo as Moment[])
  .sort((a, b) => a.year - b.year)

export const journeys: Journey[] = [
  {
    id: 'water-worlds',
    title: 'Living with water',
    subtitle: 'Eel channels, river works, and a well carved like a temple.',
    theme: 'survival',
    stops: ['budj-bim', 'dujiangyan', 'rani-vav'],
    art: 'survival',
    question: 'What links these very different landscapes?',
    options: [
      'People shaped water systems around local needs',
      'All used the same engineering design',
      'Every system was built by an empire',
    ],
    answer: 0,
    explanation:
      'Each place reveals knowledge of water built into a landscape. Their designs and social arrangements were different.',
    rhyme:
      'Water management joins observation, shared work and ways of organising daily life.',
    difference:
      'Gunditjmara eel husbandry, Chinese river irrigation and an Indian royal stepwell served different needs. These are comparisons, not evidence of direct transmission.',
  },
  {
    id: 'knowledge-keepers',
    title: 'How knowledge survives',
    subtitle: 'A place to study, a city of manuscripts, an ocean voyage.',
    theme: 'ideas',
    stops: ['nalanda', 'timbuktu-learning', 'hokulea'],
    art: 'networks',
    question: 'What keeps knowledge alive beyond one generation?',
    options: [
      'Writing it down is always enough',
      'People learning, practising and passing it on',
      'Keeping every tradition unchanged',
    ],
    answer: 1,
    explanation:
      'Institutions, manuscripts and embodied skills all depend on people who keep them in use.',
    rhyme:
      'Knowledge survives through communities that teach, preserve and renew it.',
    difference:
      'Buddhist study, West African Islamic scholarship and Pacific wayfinding are distinct traditions. Written records are not the only form of sophisticated knowledge.',
  },
  {
    id: 'everyday-power',
    title: 'The power of doing things together',
    subtitle: 'Bus journeys, tree planting, and a movement for peace.',
    theme: 'freedom',
    stops: ['montgomery', 'green-belt', 'liberia-peace'],
    art: 'voices',
    question: 'Where did these movements get some of their strength?',
    options: [
      'A fixed eighty-year rhythm',
      'Exactly the same political demands',
      'Networks that made sustained participation possible',
    ],
    answer: 2,
    explanation:
      'Organisation made individual actions part of a public demand. It did not make success automatic.',
    rhyme:
      'People with limited formal power can build influence through repeated, coordinated action.',
    difference:
      'Desegregation, environmental rights and ending a civil war require different strategies. Courts, institutions and wider political conditions also mattered.',
  },
  {
    id: 'shared-rules',
    title: 'The agreements behind everyday life',
    subtitle: 'Post, measurement, and the atmosphere we share.',
    theme: 'connection',
    stops: ['postal-union', 'metre-convention', 'montreal'],
    art: 'networks',
    question: 'What do these agreements have in common?',
    options: [
      'They made cooperation possible across borders',
      'They removed all disagreements',
      'They solved their problems on signing day',
    ],
    answer: 0,
    explanation:
      'Common rules allow separate participants to work together. Institutions and continued implementation make those rules useful.',
    rhyme: 'Some problems become easier when people agree on a shared system.',
    difference:
      'Moving letters, comparing measurements and controlling chemicals involve different costs and interests. A successful agreement in one area is not proof that every agreement will work.',
  },
  {
    id: 'ways-to-record',
    title: 'Knowledge takes different shapes',
    subtitle: 'Clay marks, knotted cords, and raised dots.',
    theme: 'ideas',
    stops: ['writing', 'quipu', 'braille'],
    art: 'sparks',
    question: 'What does this comparison help us notice?',
    options: [
      'All records use an alphabet',
      'The material form of information changes who can use it',
      'One system is best for every purpose',
    ],
    answer: 1,
    explanation:
      'A record depends on its material, its conventions and the people who know how to use it.',
    rhyme:
      'People give information a lasting, shareable form—but access depends on skills and design.',
    difference:
      'Cuneiform writing, numerical quipus and Braille are not interchangeable systems. Braille represents existing languages; quipus served different kinds of record-keeping.',
  },
  {
    id: 'built-worlds',
    title: 'The cities we make',
    subtitle: 'Three landscapes. Three answers to living together.',
    theme: 'power',
    stops: ['caral', 'angkor', 'chan-chan'],
    art: 'cities',
    question: 'What can a city’s shape reveal?',
    options: [
      'Who held resources, and how people organised life',
      'Exactly what every resident believed',
      'That all societies develop in the same order',
    ],
    answer: 0,
    explanation:
      'Platforms, canals, and walled compounds tell us something about shared work and power. They cannot reveal every person’s experience.',
    rhyme:
      'Large settlements need ways to organise people, resources, and space. Their buildings leave traces of those choices.',
    difference:
      'Andean and Khmer societies had different environments and institutions. Similar needs do not prove direct contact or a universal sequence.',
  },
  {
    id: 'words',
    title: 'The first viral ideas',
    subtitle: 'From a carved block to a connected planet.',
    theme: 'ideas',
    stops: ['diamond', 'gutenberg', 'web'],
    art: 'sparks',
    question: 'What connects these three moments?',
    options: [
      'They made ideas easier to copy',
      'They happened every 80 years',
      'They gave everyone equal access',
    ],
    answer: 0,
    explanation:
      'Each lowered a barrier to sharing information. None made access equal, and their dates do not follow a fixed rhythm.',
    rhyme:
      'When copying gets easier, more people can put ideas into circulation. Authority has new voices to contend with.',
    difference:
      'Woodblocks, metal type, and the Web had different costs, audiences, and gatekeepers. Similarity is not sameness.',
  },
  {
    id: 'routes',
    title: 'Nothing travels alone',
    subtitle: 'Follow the invisible cargo of a connected world.',
    theme: 'connection',
    stops: ['silk', 'zimbabwe', 'telegraph'],
    art: 'networks',
    question: 'What else travels when people connect?',
    options: [
      'Only the goods they intend to trade',
      'Skills, beliefs, and unexpected consequences',
      'Exactly the same ideas everywhere',
    ],
    answer: 1,
    explanation:
      'Connections carry more than cargo. People exchange techniques and stories; wider networks can also transmit danger.',
    rhyme:
      'New connections change what distant people can exchange—and make their lives more dependent on one another.',
    difference:
      'Caravan trade, Indian Ocean exchange, and electrical signals moved at radically different speeds. These are comparisons, not a single direct chain.',
  },
  {
    id: 'voices',
    title: 'Who gets a say?',
    subtitle: 'Three doors that ordinary people pushed open.',
    theme: 'freedom',
    stops: ['nz-vote', 'australia', 'south-africa'],
    art: 'voices',
    question: 'Did each breakthrough instantly create equality?',
    options: [
      'Yes, a new law solves everything',
      'No, changing a rule opens a longer struggle',
      'They all granted the same right',
    ],
    answer: 1,
    explanation:
      'Voting rights, constitutional recognition, and the end of racial exclusion are different changes. Each left unfinished work.',
    rhyme:
      'Excluded people organise, make their claims visible, and push institutions to change.',
    difference:
      'These campaigns challenged different systems. The Australian referendum, in particular, was not the moment Aboriginal people first got the vote.',
  },
  {
    id: 'disease',
    title: 'The invisible passenger',
    subtitle: 'When the things connecting us carry danger.',
    theme: 'survival',
    stops: ['plague', 'flu', 'covid'],
    art: 'survival',
    question: 'Does a similar crisis mean the same outcome?',
    options: [
      'Yes, history follows a script',
      'No, knowledge and choices change what happens',
      'Only if exactly 80 years pass',
    ],
    answer: 1,
    explanation:
      'These diseases, societies, and responses differed. A recurring vulnerability is not a prediction of an identical future.',
    rhyme:
      'Disease crosses social networks, disrupts daily routines, and tests how people care for one another.',
    difference:
      'Plague, influenza, and COVID-19 have different pathogens, transmission patterns, and mortality. Modern medicine changed the possibilities.',
  },
  {
    id: 'freedom',
    title: 'Freedom, for whom?',
    subtitle: 'A promise crosses an ocean—and gets challenged.',
    theme: 'freedom',
    stops: ['america', 'france', 'haiti'],
    art: 'voices',
    question: 'Why does Haiti change this story?',
    options: [
      'It simply copied the American Revolution',
      'Enslaved people made freedom a demand of their own',
      'All three revolutions had identical goals',
    ],
    answer: 1,
    explanation:
      'The Haitian Revolution confronted slavery itself. People excluded from declarations of liberty fought to make that liberty real.',
    rhyme:
      'The language of rights can escape the limits its first authors imagined.',
    difference:
      'The Haitian Revolution overthrew a slave system. That was not the result of the American Revolution, whose new state preserved slavery.',
  },
  {
    id: 'possibility',
    title: 'The future was not inevitable',
    subtitle: 'From one risky experiment to a world without smallpox.',
    theme: 'survival',
    stops: ['jenner', 'smallpox', 'covid'],
    art: 'sparks',
    question: 'What made smallpox eradication possible?',
    options: [
      'Waiting for the next historical cycle',
      'Knowledge, cooperation, and a disease that could be targeted',
      'One lone genius working alone',
    ],
    answer: 1,
    explanation:
      'A vaccine mattered, but so did surveillance, health workers, international coordination, and smallpox’s biology.',
    rhyme:
      'People can learn, organise, and change the course of a crisis. History includes breakthroughs, not only repeats.',
    difference:
      'Smallpox eradication cannot be assumed for every virus. The comparison shows both the power and the limits of historical analogy.',
  },
  {
    id: 'pacific',
    title: 'An ocean of unfinished promises',
    subtitle: 'Authority, independence, and belonging in the Pacific.',
    theme: 'freedom',
    stops: ['waitangi', 'samoa', 'mabo'],
    art: 'networks',
    question: 'Are these three versions of the same struggle?',
    options: [
      'Yes, their histories are interchangeable',
      'No, but each asks whose authority is recognised',
      'Yes, and each ended every disagreement',
    ],
    answer: 1,
    explanation:
      'A treaty, national independence, and native title are different questions. Reading them together can reveal a common concern without erasing distinct peoples and histories.',
    rhyme:
      'Communities challenge systems that decide who controls land and political life.',
    difference:
      'Samoan independence created a sovereign state. Mabo recognised native title within Australian law. Te Tiriti involves promises and meanings that must be understood on their own terms.',
  },
]

export const momentById = Object.fromEntries(
  moments.map((m) => [m.id, m]),
) as Record<string, Moment>
